application: htwwg
version: 1
runtime: python27
api_version: 1
threadsafe: no
env_variables:
  DJANGO_SETTINGS_MODULE: 'myapp.settings'

handlers:
- url: /.*
  script: birthDetails.py

libraries:
- name: django
  version: "latest"

